services:
  postgres:
    image: postgres:latest
    ports:
      - '3300:3306'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password


        
        
        
        
